### ISSUE TITLE
 binary link in readme is dead

### ISSUE THREAD

**Issue by thenoobtester** [DatBrick/OpenMM2#3]
Hi,

could you please re-upload OpenMM2.zip the link in the readme is dead?

Thank you so much for this, I had so much with this game and OpenMM1 was awesome for bringing it back.

**Comment by 0x1F9F1** [comment]
I've triggered a rebuild so it should be available shortly after this message, though as the readme says the project is abandoned, and you wont get the same kind of experience as open1560 provides. For bugfixes mm2hook is a better option

**Comment by thenoobtester** [comment]
Thank you for this, ok I will have a look at mm2hook.

PS:The build seems to not be finished yet, is it normal? As when I click on the Latest Version link it still shows "{"message":"Artifact not found or access denied."}"

**Comment by thenoobtester** [comment]
My mistake, I removed the ?branch=master from the link and it worked :)
